services:

  localRabbitMQ:
    image: public.ecr.aws/docker/library/rabbitmq:3.12.14-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672